[[pages]]
path = "src/agent_configurations.py"
name = "Configure your Agents"
icon = "âš™ï¸"

[[pages]]
path = "src/run_ai_agent_ocr.py"
name = "Run AI Agent OCR"
icon = "ğŸ“ˆ"

[[pages]]
path = "src/run_single_agent.py"
name = "Run Single Agent"
icon = "ğŸ¤–"
